import type { DoctorArea, Provider } from "@/types";

export const doctorsHero = {
  breadcrumb: { home: "HOME", current: "OUR DOCTORS" },
  eyebrow: "OUR DOCTORS",
  titleStart: "Board-certified doctors with ",
  titleHighlight: "10+ years",
  titleEnd: " of experience.",
  description:
    "Our network has 61 providers ready to care for your child across 24 clinics in Southern California, plus telehealth visits. Many of our physicians are on staff at some of the most reputable hospitals in Los Angeles.",
  primaryCta: { label: "FIND A DOCTOR", href: "#finder" },
  secondaryCta: { label: "GET IN TOUCH", href: "/contact-us" },
  director: {
    badge: "MEDICAL DIRECTOR",
    name: "Janesri De Silva",
    credentials: "MD, FAAP · BOARD CERTIFIED",
    image: "/images/doctors/janesri-de-silva.webp",
    imageAlt: "Dr. Janesri De Silva",
  },
};

export const affiliated = {
  eyebrow: "WE ARE AFFILIATED",
  title: "Join the largest pediatric medical group in Los Angeles.",
  lead: "Benefit from Kids & Teens Medical Group",
  description:
    "Our partnership gives members access to a comprehensive range of pediatric services, including well-child check-ups, immunizations, and treatment for acute and chronic illnesses, from preventive care to urgent care and more.",
  cta: { label: "GET IN TOUCH", href: "/contact-us" },
  image: "/images/affiliated.webp",
  imageAlt: "Pediatrician giving a high five to a young patient",
  group: {
    name: "Kids & Teens Medical Group",
    href: "https://www.ktdoctor.com/",
    logo: "/images/partners/kids-and-teens.webp",
  },
};

export const finder = {
  eyebrow: "FIND A DOCTOR IN YOUR AREA",
  title: "Choose your area.",
  description:
    "Select the area you are in or near to see the doctors available. Visit any clinic listed and your records sync to that clinic immediately.",
  searchLabel: "Search providers",
  searchPlaceholder: "Search a provider by name",
  clear: "CLEAR",
  allAreas: "All Areas",
  syncNote: "RECORDS SYNC AT EVERY CLINIC ✦",
  noResults: "No providers match that name.",
  view: "VIEW PROFILE ▸",
  searchResults: "Search results",
  one: "PROVIDER",
  many: "PROVIDERS",
  available: "AVAILABLE",
  virtual: "VIRTUAL VISITS",
};

export const profileDialog = {
  badge: "PROVIDER PROFILE",
  specialty: "PEDIATRICS",
  seesAt: "SEES PATIENTS AT",
  book: "BOOK ONLINE",
  fallbackBookHref: "https://www.ktdoctor.com/",
  close: "Close",
};

export const areas: DoctorArea[] = [
  {
    id: "agoura-hills",
    name: "Agoura Hills",
  },
  {
    id: "arcadia",
    name: "Arcadia",
  },
  {
    id: "beverly-hills",
    name: "Beverly Hills",
  },
  {
    id: "camarillo",
    name: "Camarillo",
  },
  {
    id: "canyon-country",
    name: "Canyon Country",
  },
  {
    id: "culver-city",
    name: "Culver City",
  },
  {
    id: "downey",
    name: "Downey",
  },
  {
    id: "glendale",
    name: "Glendale",
  },
  {
    id: "hollywood",
    name: "Hollywood",
  },
  {
    id: "la-canada",
    name: "La Cañada Flintridge",
  },
  {
    id: "la-mirada",
    name: "La Mirada",
  },
  {
    id: "mission-hills",
    name: "Mission Hills",
  },
  {
    id: "northridge",
    name: "Northridge",
  },
  {
    id: "pasadena",
    name: "Pasadena",
  },
  {
    id: "pico-rivera",
    name: "Pico Rivera",
  },
  {
    id: "san-fernando",
    name: "San Fernando",
  },
  {
    id: "san-pedro",
    name: "San Pedro",
  },
  {
    id: "santa-monica",
    name: "Santa Monica",
  },
  {
    id: "tarzana",
    name: "Tarzana",
  },
  {
    id: "torrance",
    name: "Torrance",
  },
  {
    id: "valencia",
    name: "Valencia",
  },
  {
    id: "van-nuys",
    name: "Van Nuys",
  },
  {
    id: "west-hills",
    name: "West Hills",
  },
  {
    id: "whittier",
    name: "Whittier",
  },
  {
    id: "telehealth",
    name: "Telehealth",
  },
];

/** Older links used short area hashes (for example #van). Map them to the current ids. */
export const legacyAreaHashes: Record<string, string> = {
  agoura: "agoura-hills",
  beverly: "beverly-hills",
  canyon: "canyon-country",
  culver: "culver-city",
  lacanada: "la-canada",
  lamirada: "la-mirada",
  mission: "mission-hills",
  pico: "pico-rivera",
  sanfernando: "san-fernando",
  santamonica: "santa-monica",
  van: "van-nuys",
  west: "west-hills",
};

export const providers: Provider[] = [
  {
    id: "adrienne-altman",
    name: "Adrienne C. Altman",
    credentials: "MD",
    areas: ["valencia"],
    bookingUrl: "https://healow.com/apps/provider/adrienne-altman-3156393",
    bio: "Grew up in Pennsylvania and New York. Undergraduate at Cornell University; medical school at SUNY Syracuse. Completed pediatric residency and a Pediatric Hematology/Oncology fellowship at UCLA before joining Dr. Greenwald in Valencia. Enjoys dressage riding.",
    image: "/images/doctors/adrienne-altman.webp",
  },
  {
    id: "ahoo-sahba",
    name: "Ahoo Sahba",
    credentials: "MD",
    areas: ["van-nuys"],
    bookingUrl: "https://healow.com/apps/provider/ahoo-sahba-3161338",
    bio: "",
    image: "/images/doctors/ahoo-sahba.webp",
  },
  {
    id: "amrita-dosanjh",
    name: "Amrita Dosanjh",
    credentials: "MD",
    areas: ["west-hills", "northridge", "agoura-hills"],
    bookingUrl: "https://healow.com/apps/provider/amrita-dosanjh-3161324",
    bio: "",
    image: "/images/doctors/amrita-dosanjh.webp",
  },
  {
    id: "azam-jazayeri",
    name: "Azam Jazayeri",
    credentials: "MD",
    areas: ["culver-city"],
    bookingUrl: "https://healow.com/apps/provider/azam-jazayeri-3161350",
    bio: "",
    image: "/images/doctors/azam-jazayeri.webp",
  },
  {
    id: "banpreet-samra",
    name: "Banpreet Samra",
    credentials: "PA",
    areas: ["northridge", "west-hills", "tarzana"],
    bookingUrl: "https://healow.com/apps/provider/banpreet-samra-3672038",
    bio: "",
    image: null,
  },
  {
    id: "barbara-rodriguez",
    name: "Barbara Rodriguez",
    credentials: "MD, FAAP",
    areas: ["pasadena"],
    bookingUrl: "https://healow.com/apps/provider/barbara-rodriguez-3161337",
    bio: "Joined Kids & Teens Medical Group in 1989 and now serves as Co-Medical Director, with over 30 years of pediatric experience. A native Angeleno, she earned her degree in Biological Sciences from USC and her medical degree from Creighton University, completing her pediatric internship and residency at LAC+USC Medical Center. Bilingual in English and Spanish, she volunteers as an Assistant Clinical Professor for UCLA School of Nursing. Outside work she enjoys soccer, scuba diving, cooking, and family time.",
    image: "/images/doctors/barbara-rodriguez.webp",
  },
  {
    id: "benjamin-behroozan",
    name: "Benjamin Behroozan",
    credentials: "MD",
    areas: ["hollywood", "santa-monica"],
    bookingUrl: "https://healow.com/apps/provider/benjamin-behroozan-3350334",
    bio: "",
    image: "/images/doctors/benjamin-behroozan.webp",
  },
  {
    id: "brian-bhatt",
    name: "Brian Bhatt",
    credentials: "MD, FAAP",
    areas: ["northridge", "west-hills", "valencia"],
    bookingUrl: "https://healow.com/apps/provider/brian-bhatt-3156398",
    bio: "Earned his Bachelor's in Biological Sciences from the University of Connecticut and his MD from St. George's University School of Medicine, then completed a three-year pediatric residency at NYU Langone Long Island Hospital. Fluent in English and Gujarati. Outside medicine he enjoys cooking, tennis, the beach, collecting vintage watches, and Marvel movie nights with family.",
    image: "/images/doctors/brian-bhatt.webp",
  },
  {
    id: "carolina-ungs",
    name: "Carolina Ungs",
    credentials: "MD",
    areas: ["pico-rivera", "downey"],
    bookingUrl: "https://healow.com/apps/provider/carolina-ungs-3161341",
    bio: "",
    image: "/images/doctors/carolina-ungs.webp",
  },
  {
    id: "carolyn-czaplicki",
    name: "Carolyn Czaplicki",
    credentials: "DO",
    areas: ["san-pedro"],
    bookingUrl: "https://healow.com/apps/provider/carolyn-czaplicki-4048106",
    bio: "",
    image: "/images/doctors/carolyn-czaplicki.webp",
  },
  {
    id: "casie-mcguire",
    name: "Casie McGuire",
    credentials: "FNP-C",
    areas: ["valencia", "canyon-country"],
    bookingUrl: "https://healow.com/apps/provider/casie-mcguire-3654055",
    bio: "",
    image: "/images/doctors/casie-mcguire.webp",
  },
  {
    id: "cze-ja-tam",
    name: "Cze-Ja Tam",
    credentials: "PNP",
    areas: ["west-hills"],
    bookingUrl: "https://healow.com/apps/provider/czeja-tam-3672058",
    bio: "",
    image: "/images/doctors/cze-ja-tam.webp",
  },
  {
    id: "erik-saenz",
    name: "Erik Saenz",
    credentials: "NP",
    areas: ["whittier"],
    bookingUrl: "https://healow.com/apps/provider/erik-saenz-3672034",
    bio: "",
    image: null,
  },
  {
    id: "faiza-iram",
    name: "Faiza Iram",
    credentials: "MD, FAAP",
    areas: ["downey"],
    bookingUrl: "https://healow.com/apps/provider/faiza-iram-3672054",
    bio: "Fluent in English, Hindi/Urdu, Spanish, and Punjabi. Earned her medical degree from Universidad Iberoamericana School of Medicine in the Dominican Republic and completed her pediatrics residency at the University of Medicine and Dentistry of New Jersey. Passionate about understanding patients' cultural backgrounds to provide optimal care, and an advocate for vaccines and breastfeeding support. Enjoys hiking and cooking spicy Pakistani food.",
    image: "/images/doctors/faiza-iram.webp",
  },
  {
    id: "fatemeh-anari",
    name: "Fatemeh Anari",
    credentials: "PA-C",
    areas: ["northridge"],
    bookingUrl: "https://healow.com/apps/provider/fatemeh-anari-3156394",
    bio: "",
    image: "/images/doctors/fatemeh-anari.webp",
  },
  {
    id: "greta-vines-douglas",
    name: "Greta Vines-Douglas",
    credentials: "PA",
    areas: ["san-pedro"],
    bookingUrl: "https://healow.com/apps/provider/greta-vinesdouglas-4048111",
    bio: "",
    image: "/images/doctors/greta-vines-douglas.webp",
  },
  {
    id: "hilma-benjamin",
    name: "Hilma Benjamin",
    credentials: "MD, FAAP",
    areas: ["northridge", "west-hills"],
    bookingUrl: "https://healow.com/apps/provider/hilma-benjamin-3156397",
    bio: "Graduated from the University of the Virgin Islands with a BS in biology, earned an MS in molecular and cellular biology from University of Maryland, Baltimore County, and received her MD from Penn State College of Medicine. Completed her pediatrics residency at All Children's Hospital and Tampa General Hospital, and serves as acting Medical Director of Extended Hours/After Hours Care. Special interests include child behavior, growth and development, dental care, nutrition, and physical education.",
    image: "/images/doctors/hilma-benjamin.webp",
  },
  {
    id: "janesri-de-silva",
    name: "Janesri De Silva",
    credentials: "MD, FAAP",
    areas: ["la-canada"],
    bookingUrl: "https://healow.com/apps/provider/janesri-desilva-3161323",
    bio: "Medical Director for General Pediatrics and Adolescent Medicine. Earned her bachelor's in neuroscience from UCLA and her medical degree from the American University of the Caribbean, completing her pediatric residency at Kaiser Permanente Sunset and a fellowship in Adolescent Medicine at Children's Hospital Los Angeles. Chaired Northridge Hospital's pediatric department from 2014-2016. Bilingual, a mother of two, and enjoys yoga, dance, and piano.",
    image: "/images/doctors/janesri-de-silva.webp",
  },
  {
    id: "jenifer-chungafung",
    name: "Jenifer Chungafung",
    credentials: "MD",
    areas: ["la-mirada"],
    bookingUrl: "https://healow.com/apps/provider/jenifer-chungafung-3636023",
    bio: "",
    image: "/images/doctors/jenifer-chungafung.webp",
  },
  {
    id: "jocelyn-zuniga",
    name: "Jocelyn Zuniga",
    credentials: "MD, FAAP",
    areas: ["arcadia", "downey"],
    bookingUrl: "https://healow.com/apps/provider/jocelyn-zuniga-3161348",
    bio: "",
    image: "/images/doctors/jocelyn-zuniga.webp",
  },
  {
    id: "jose-vargas",
    name: "Jose Vargas",
    credentials: "PA",
    areas: ["san-fernando", "van-nuys"],
    bookingUrl: "https://healow.com/apps/provider/jose-vargas-3161343",
    bio: "Brings 35 years of experience in pediatric and family medicine in the San Fernando Valley. Completed the physician assistant program in family practice and pediatrics at Charles R. Drew University of Medicine and Science. Enjoys camping, hiking, and cycling, and promotes a healthy lifestyle to his patients and their families.",
    image: "/images/doctors/jose-vargas.webp",
  },
  {
    id: "laurie-beth-juarez-morales",
    name: "Laurie Beth Juarez-Morales",
    credentials: "MD",
    areas: ["san-fernando", "west-hills", "van-nuys"],
    bookingUrl: "https://healow.com/apps/provider/lauriebeth-juarezmorales-3161351",
    bio: "Born and raised in the San Fernando Valley, where she has practiced for over a decade. Earned a molecular biology degree with an education minor from UCLA, conducting research at UCLA's Multiple Sclerosis Laboratory, before attending Loma Linda School of Medicine and completing her pediatric residency at UC Irvine. Fluent in Spanish and Tagalog. Former/incumbent Department Chair of Pediatrics at Pacifica Hospital of the Valley.",
    image: "/images/doctors/laurie-beth-juarez-morales.webp",
  },
  {
    id: "luis-garcia",
    name: "Luis Garcia",
    credentials: "PNP",
    areas: ["pico-rivera", "downey", "whittier"],
    bookingUrl: "https://healow.com/apps/provider/luis-garcia-3350331",
    bio: "",
    image: "/images/doctors/luis-garcia.webp",
  },
  {
    id: "mario-cuevas",
    name: "Mario Cuevas",
    credentials: "PA",
    areas: ["la-mirada"],
    bookingUrl: "https://healow.com/apps/provider/mario-cuevas-3636024",
    bio: "",
    image: null,
  },
  {
    id: "maria-vega",
    name: "Maria Vega",
    credentials: "PNP",
    areas: ["downey"],
    bookingUrl: "https://healow.com/apps/provider/maria-vega-3161344",
    bio: "",
    image: null,
  },
  {
    id: "mark-snyder",
    name: "Mark Snyder",
    credentials: "MD, FAAP",
    areas: ["west-hills", "agoura-hills"],
    bookingUrl: "https://healow.com/apps/provider/mark-snyder-3161340",
    bio: "Joined Kids & Teens Medical Group in 2017. A California native from Woodland Hills, he earned his Bachelor of Science in Bioengineering from UC San Diego and his MD from the University of Kansas Medical School, completing his pediatrics residency at Cedars-Sinai Medical Center. Outside work he enjoys mountain biking, kayaking, astronomy, and following current events.",
    image: "/images/doctors/mark-snyder.webp",
  },
  {
    id: "martin-fineberg",
    name: "Martin Fineberg",
    credentials: "MD, FAAP",
    areas: ["beverly-hills", "torrance"],
    bookingUrl: "https://healow.com/apps/provider/martin-fineberg-3161325",
    bio: "Has practiced in the San Fernando Valley since 1988. A native of Melbourne, Australia, he studied medicine at the University of Melbourne and trained in pediatrics at the Royal Children's Hospital Melbourne before completing his residency at Emory University in Atlanta and additional neonatology training at Children's Hospital Los Angeles. Licensed in California and Australia, he has special interest in high-risk NICU graduates and children with pulmonary diseases.",
    image: "/images/doctors/martin-fineberg.webp",
  },
  {
    id: "michael-green",
    name: "Michael Green",
    credentials: "PA",
    areas: ["san-pedro"],
    bookingUrl: "https://healow.com/apps/provider/michael-green-4048674",
    bio: "",
    image: null,
  },
  {
    id: "miguel-sutter",
    name: "Miguel Sutter",
    credentials: "PA-C",
    areas: ["van-nuys", "mission-hills"],
    bookingUrl: "https://healow.com/apps/provider/miguel-sutter-3161356",
    bio: "A Certified Physician Assistant with over 24 years of experience and father of two. Hobbies include cycling, running, skiing, and spending time with family. Passionate about helping people.",
    image: "/images/doctors/miguel-sutter.webp",
  },
  {
    id: "monique-craig",
    name: "Monique Craig",
    credentials: "PA",
    areas: ["culver-city"],
    bookingUrl: "https://healow.com/apps/provider/monique-craig-3161322",
    bio: "",
    image: "/images/doctors/monique-craig.webp",
  },
  {
    id: "oliver-petalver",
    name: "Oliver Petalver",
    credentials: "PA-C",
    areas: ["downey"],
    bookingUrl: "https://healow.com/apps/provider/oliver-petalver-3161334",
    bio: "",
    image: "/images/doctors/oliver-petalver.webp",
  },
  {
    id: "palak-shelat",
    name: "Palak Shelat",
    credentials: "MD, FAAP",
    areas: ["northridge", "pasadena", "valencia", "canyon-country"],
    bookingUrl: "https://healow.com/apps/provider/palak-shelat-3161339",
    bio: "Fluent in English, Gujarati, and Hindi. Born and raised in India, she came to the USA as a teenager. Earned her Bachelor's in Biological Sciences from the University of Connecticut as a New England Scholar and her MD from St. George's University School of Medicine with high honors, completing her pediatric residency at NYU Langone Long Island Hospital. Enjoys painting, tennis, meditation, yoga, and long walks on the beach.",
    image: "/images/doctors/palak-shelat.webp",
  },
  {
    id: "rena-keynigshteyn",
    name: "Rena Keynigshteyn",
    credentials: "MD",
    areas: ["tarzana", "culver-city"],
    bookingUrl: "https://healow.com/apps/provider/rena-keynigshteyn-3161353",
    bio: "Has over 30 years dedicated to pediatric health. A graduate of Tashkent Pediatric Medical Institute, she completed her internship at Brookdale University Hospital and residency at White Memorial Medical Center, and treated children and adolescents in Culver City for 15 years before joining Kids & Teens Medical Group. A fluent Russian speaker.",
    image: "/images/doctors/rena-keynigshteyn.webp",
  },
  {
    id: "rohina-furmuly",
    name: "Rohina Furmuly",
    credentials: "PA-C",
    areas: ["beverly-hills", "west-hills", "culver-city"],
    bookingUrl: "https://healow.com/apps/provider/rohina-furmuly-3161326",
    bio: "A nationally board-certified physician assistant with a Bachelor of Science in physiological science from UCLA and a Master of Science in physician assistant studies from Western University of Health Sciences. Previously served veterans at the Department of Veterans Affairs Community Based Outpatient Clinic in Ventura County. Her research background includes work with UCLA Nuclear Medicine, Kaiser Permanente, and Amgen on Alzheimer's disease and dementia, with two co-authored publications. An avid traveler who enjoys reading, outdoor activities, and charitable work.",
    image: "/images/doctors/rohina-furmuly.webp",
  },
  {
    id: "roobina-hakoopian",
    name: "Roobina Hakoopian",
    credentials: "NP",
    areas: ["pasadena"],
    bookingUrl: "https://healow.com/apps/provider/roobina-hakoopian-3672056",
    bio: "",
    image: null,
  },
  {
    id: "sharmetha-ramanan",
    name: "Sharmetha Ramanan",
    credentials: "PNP",
    areas: ["pasadena"],
    bookingUrl: "https://healow.com/apps/provider/sharmetha-ramanan-3161335",
    bio: "Earned her master's in pediatric nursing from Massachusetts General Hospital's Institute of Health Professions in Boston. Her pediatric career began volunteering at children's hospitals in Sri Lanka, and includes experience as a medical assistant at an Australian children's heart and lung center and research on infant neuro-cognitive development at Boston Children's Hospital.",
    image: "/images/doctors/sharmetha-ramanan.webp",
  },
  {
    id: "tatiana-genjoyan",
    name: "Tatiana Genjoyan",
    credentials: "PNP",
    areas: ["la-canada"],
    bookingUrl: "https://healow.com/apps/provider/tatiana-genjoyan-3272030",
    bio: "",
    image: "/images/doctors/tatiana-genjoyan.webp",
  },
  {
    id: "tisha-pison",
    name: "Tisha Pison",
    credentials: "PNP",
    areas: ["downey"],
    bookingUrl: "https://healow.com/apps/provider/tisha-pison-3161358",
    bio: "",
    image: "/images/doctors/tisha-pison.webp",
  },
  {
    id: "victor-tamashiro",
    name: "Victor Tamashiro",
    credentials: "MD",
    areas: ["mission-hills"],
    bookingUrl: "https://healow.com/apps/provider/victor-tamashiro-3161357",
    bio: "",
    image: "/images/doctors/victor-tamashiro.webp",
  },
  {
    id: "yussef-sakhai",
    name: "Yussef Sakhai",
    credentials: "MD",
    areas: ["beverly-hills", "culver-city", "santa-monica"],
    bookingUrl: "https://healow.com/apps/provider/yussef-sakhai-3672037",
    bio: "",
    image: "/images/doctors/yussef-sakhai.webp",
  },
  {
    id: "lisa-gutierrez",
    name: "Lisa Gutierrez",
    credentials: "NP",
    areas: ["la-canada"],
    bookingUrl: "https://healow.com/apps/provider/lisa-gutierrez-3374487",
    bio: "",
    image: null,
  },
  {
    id: "alea-sohn",
    name: "Alea Sohn",
    credentials: "NP",
    areas: ["torrance"],
    bookingUrl: "https://healow.com/apps/provider/alea-sohn-3672062",
    bio: "",
    image: null,
  },
  {
    id: "breanna-kikuchi",
    name: "Breanna Kikuchi",
    credentials: "NP",
    areas: ["downey"],
    bookingUrl: "https://healow.com/apps/provider/breanna-kikuchi-3602227",
    bio: "",
    image: null,
  },
  {
    id: "christine-sapinoso",
    name: "Christine Sapinoso",
    credentials: "NP",
    areas: ["northridge"],
    bookingUrl: "https://healow.com/apps/provider/christine-sapinoso-3672039",
    bio: "",
    image: null,
  },
  {
    id: "clarissa-gooze",
    name: "Clarissa Gooze",
    credentials: "NP",
    areas: ["torrance"],
    bookingUrl: "https://healow.com/apps/provider/clarissa-gooze-3794996",
    bio: "",
    image: "/images/doctors/clarissa-gooze.webp",
  },
  {
    id: "david-razi",
    name: "David Razi",
    credentials: "MD",
    areas: ["hollywood"],
    bookingUrl: "https://healow.com/apps/provider/david-razi-3672036",
    bio: "",
    image: null,
  },
  {
    id: "delaram-halavi",
    name: "Delaram Halavi",
    credentials: "PA",
    areas: ["beverly-hills"],
    bookingUrl: "https://healow.com/apps/provider/delaram-halavi-3672055",
    bio: "",
    image: null,
  },
  {
    id: "ernestine-njie",
    name: "Ernestine Njie",
    credentials: "NP",
    areas: ["hollywood"],
    bookingUrl: "https://healow.com/apps/provider/ernestine-njie-3672053",
    bio: "",
    image: null,
  },
  {
    id: "helen-pensanti",
    name: "Helen Pensanti",
    credentials: "MD",
    areas: ["glendale", "la-mirada"],
    bookingUrl: "https://healow.com/apps/provider/helen-pensanti-3672050",
    bio: "",
    image: "/images/doctors/helen-pensanti.webp",
  },
  {
    id: "jasmine-berookim",
    name: "Jasmine Berookim",
    credentials: "MD",
    areas: ["la-mirada"],
    bookingUrl: "https://healow.com/apps/provider/jasmine-berookim-3672041",
    bio: "",
    image: null,
  },
  {
    id: "lisa-tan",
    name: "Lisa Tan",
    credentials: "NP",
    areas: ["northridge", "la-canada"],
    bookingUrl: "https://healow.com/apps/provider/lisa-tan-3672060",
    bio: "",
    image: null,
  },
  {
    id: "lousine-frandjian",
    name: "Lousine Frandjian",
    credentials: "NP",
    areas: ["pasadena", "la-canada", "arcadia"],
    bookingUrl: "https://healow.com/apps/provider/lousine-frandjian-3672046",
    bio: "",
    image: null,
  },
  {
    id: "ruth-gabay",
    name: "Ruth Gabay",
    credentials: "NP",
    areas: ["hollywood"],
    bookingUrl: "https://healow.com/apps/provider/ruth-gabay-3672047",
    bio: "",
    image: null,
  },
  {
    id: "sonal-patel",
    name: "Sonal Patel",
    credentials: "MD",
    areas: ["la-canada"],
    bookingUrl: "https://healow.com/apps/provider/sonal-patel-3672049",
    bio: "",
    image: "/images/doctors/sonal-patel.webp",
  },
  {
    id: "trish-reyes",
    name: "Trish Reyes",
    credentials: "NP",
    areas: ["telehealth"],
    bookingUrl: "https://healow.com/apps/provider/trish-reyes-3161336",
    bio: "Trish Reyes is a Family Nurse Practitioner Board Certified. She has over 25 years of experience in the medical field. Trish provides continuing and comprehensive healthcare for the individual and family across all ages, genders, diseases, and body systems in Primary Care. The emphasis of the holistic nature of health the knowledge of the patient in the context of the family and the community, emphasizing disease, prevention, and health promotion.",
    image: "/images/doctors/trish-reyes.webp",
  },
  {
    id: "yeongbu-kim",
    name: "Yeongbu Kim",
    credentials: "NP",
    areas: ["van-nuys", "glendale", "hollywood", "la-mirada"],
    bookingUrl: "https://healow.com/apps/provider/yeongbu-kim-3653936",
    bio: "",
    image: null,
  },
  {
    id: "brianne-guevara",
    name: "Brianne Guevara",
    credentials: "CPNP",
    areas: ["camarillo"],
    bookingUrl: "",
    bio: "",
    image: null,
  },
  {
    id: "deborah-marlow-mejia",
    name: "Deborah Marlow-Mejia",
    credentials: "MD",
    areas: ["camarillo"],
    bookingUrl: "",
    bio: "",
    image: null,
  },
  {
    id: "heidi-erickson",
    name: "Heidi Erickson",
    credentials: "CPNP",
    areas: ["camarillo"],
    bookingUrl: "",
    bio: "",
    image: null,
  },
  {
    id: "jon-dandrea",
    name: "Jon D'Andrea",
    credentials: "MD",
    areas: ["camarillo"],
    bookingUrl: "",
    bio: "",
    image: null,
  },
  {
    id: "lynn-garcia-galan",
    name: "Lynn Garcia-Galan",
    credentials: "MD",
    areas: ["camarillo"],
    bookingUrl: "",
    bio: "",
    image: null,
  },
];
